### ISSUE TITLE
Retrieve urls / statistics

### ISSUE THREAD

**Issue by LBegnaud** [sjkp/UrlShortener#1]
I have this working per the blog post, but I'm not well-versed with azure enough to know how to retrieve data from the storage tables. What would be the simplest way to list that data?

**Comment by sjkp** [comment]
Hi @LBegnaud I wrote a blog post on how I would do the analytics using power bi, http://wp.sjkp.dk/azure-functions-shortcode-analytics/

**Comment by LBegnaud** [comment]
Cool I'll take a look

Thanks!

**Comment by LBegnaud** [comment]
Hmm @sjkp i don't see the changes you made to clean up clientIP

Otherwise great writeup!

**Comment by sjkp** [comment]
@LBegnaud yes, I have commited the changes now. Look in https://github.com/sjkp/UrlShortener/blob/master/UrlShortener/Redirect/run.csx for the changes. 

Also commited my powerbi file for reference, but it is using the OData Azure Table endpoint, so it will not work when more than 1000 elements are in the analytics table, use the method described in the blog post instead.
